services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "${APP_PORT}:8000"

    command: "uvicorn --factory application.api.main:create_application --timeout-graceful-shutdown 2 --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app/:/app/
    env_file:
      - .env
  
  cache:
    image: redis
    container_name: cache
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "${CACHE_PORT}:6379"
    volumes:
      - ./redisdata:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  mongodb:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:?}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    ports:
      - "${DB_PORT}:27017"


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:?}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:?}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME:?}:${MONGO_PASSWORD:?}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

